### ISSUE TITLE
Unable to read nrrd files python

### ISSUE THREAD

**Issue by kishanbala** [mhe/pynrrd#105]
Hi,
   I am working on a segmentation project in which my images and masks are in nrrd file format. Within an nrrd file, there are 900 slices of data. I would like to read them and convert them to numpy arrays or pytorch tensors. I could not find a solution. Been stuck at this point for more than a week. Kindly help!!!!

**Comment by addisonElliott** [comment]
Sorry for the late response. The example on the README should be enough to get you started with using this library and reading in NRRD files.

By default, pynrrd reads the data and returns it as a Numpy array already. It will be up to you then to manipulate the data and transform it for pytorch use.
