### ISSUE TITLE
Additional v1.0.0 changes

### ISSUE THREAD

**Issue by addisonElliott** [mhe/pynrrd#141]
Discuss additional changes to make before releasing v1.0.0.

@bernardopericacho Were there other changes you had in mind for v1?

Additionally, have you had a chance to test the master branch to ensure it's working as expected?

**Comment by bernardopericacho** [comment]
Typing was the other thing I wanted to see and I think some support was added here https://github.com/mhe/pynrrd/pull/131
I am not anymore in the company that is using the library and needed some of these changes. I will contact them to bump the version.

Thanks for pushing these to the finish line 🚀
