### ISSUE TITLE
About the rescale intercept/slope metadata in `.nrrd` files

### ISSUE THREAD

**Issue by Masaaki-75** [mhe/pynrrd#147]
I have a few CT image data in `.nrrd` format, and I am wondering if `pynrrd` could extract from these files the rescale intercept/slope information  that translates the CT data to Hounsfield units?

I am not familiar with the metadata contained in a `.nrrd` file, so I am not sure if or not the rescale intercept/slope would be stored in this format (as in `.dcm`), and how `pynrrd` would read this information (`nrrd.read_header()` didn't help).

**Comment by addisonElliott** [comment]
This library will extract whatever header information is stored in the NRRD file. Thus, if whatever system/program that created the NRRD file added that information in the headers, then this library should be able to read it.

Off the top of my head, I’m not sure if there’s a standard header field in NRRD for this. If not, custom fields can be added easily.

I’d suggest loading the file with this library and printing the header out to see.

**Comment by Masaaki-75** [comment]
Seems that, unlike in `.dcm` files, the rescale metadata is not a standard field in `.nrrd` (I found [discussion](https://discourse.slicer.org/t/preserve-image-rescale-and-slope-when-saving-in-nrrd-file/13357) on this), so I couldn't see it in the output of `nrrd.read_header()`.

But anyway, thanks for the suggestion :)
