### ISSUE TITLE
Look at and cherry-pick from nocnokneo/pynrrd?

### ISSUE THREAD

**Issue by samueljohn** [mhe/pynrrd#15]
I've see that @nocnokneo did some commits back in 2013 that have never ended up in a PR. A pity as it seems there are basic unit tests and some minor fixes. I am considering starting with pynrrd and got a bit confused. I am not ready to make this PR but perhaps this issue can act as a reminder for someone (me or @nocnokneo or someone other) to do a clean PR.

https://github.com/nocnokneo/pynrrd

**Comment by mhe** [comment]
@nocnokneo created a PR, which is now merged. Thanks again @nocnokneo!
