### ISSUE TITLE
nptyping latest version still includes deprecated numpy value

### ISSUE THREAD

**Issue by GFleishman** [mhe/pynrrd#153]
np.bool8 was deprecated in numpy version 1.24.0
https://github.com/numpy/numpy/issues/23755

nptyping still includes this value:
https://github.com/ramonhagenaars/nptyping/issues/124

Due to pynrrd dependency on nptyping, import of pynrrd latest fails.
Keep an eye on nptyping for a fix or remove dependency as @eleftherioszisis suggests.

**Comment by addisonElliott** [comment]
Fixed in #154.

New major release pending

**Comment by mgeplf** [comment]
@addisonElliott > New major release pending

Any update on this? Do you have a timeline on when the new release would happen?
Thanks for your hard work.

**Comment by addisonElliott** [comment]
Sorry, I've been meaning to find the time to do that. Hopefully this weekend or next week. I have another feature I want to merge in and do a minor release.

I was going to do a major release, but I think it's a minor enough change that a minor will suffice.

**Comment by mgeplf** [comment]
> Sorry, I've been meaning to find the time to do that. 

No problem and thanks for the update.
