### ISSUE TITLE
Update package on PyPI?

### ISSUE THREAD

**Issue by dyf** [mhe/pynrrd#16]
I had some Windows-specific issues when I installed this package via pip.  They went away when I installed from master.   Any plans for a version bump on PyPI?

**Comment by ihnorton** [comment]
+1. @hjmjohnson's recent PRs fixed some bugs with parsing header fields (e.g. using `split()` rather than `split(' ')`)

**Comment by mhe** [comment]
The current PyPI version was not uploaded by me, so I currently do not have the rights to update it. Will investigate how I can fix that (in the meantime I already prepared a new version to be uploaded).

**Comment by nocnokneo** [comment]
No problem. @mhe, What's your pypi username?

**Comment by mhe** [comment]
@nocnokneo, sorry, forgot to mention that :) My pypi username is "mhe"

**Comment by nocnokneo** [comment]
Thanks. I've added you as an owner for the `pynrrd` package. Let me know if you have any problems.

**Comment by mhe** [comment]
@nocnokneo thank you for your quick response! It worked.

I uploaded a new version (v0.2.0) to PyPi. Let me know in case things do not work as expected.
