### ISSUE TITLE
read_header corrupts file handle

### ISSUE THREAD

**Issue by haesemeyer** [mhe/pynrrd#25]
Windows 7 x64, Python 3.5, Numpy 1.11

read(filename) does not work for me. Specifically line 269 (data = np.fromfile(datafilehandle, dtype)) results in "OSError: seeking file failed". This seems to be caused by whatever read_header does to the filehandle.
Calling read_header followed by read_data without closing the file in between (as done by a call to read) results in the error above, while the sequence (open;header=read_header;close;open;read_data;close) completes without errors and returns the correct image data.
As a quick fix I would suggest closing and re-opening the file in between the calls to read_header and read_data in the read function.
#26

**Comment by wilkij1** [comment]
I just ran into something similar today, also on Win7 x64, python 3.5. 

I was getting an exception on line 281 when reading a gzip compressed NRRD:

```decompressed_data += decompobj.decompress(chunk)```

I traced the problem back to the use of mmap on line 243 where mmap is instantiated. Following that call if you check the file position with 'datafilehandle.tell()' you find it returns -8192. The subsequent call to datafilehandle.seek() does not fix it. When the header is read it advances the header size number of bytes but is still probably negative. One quick fix is
```
m = mmap.mmap(datafilehandle.fileno(), 0, access=mmap.ACCESS_READ)
datafilehandle.tell()
datafilehandle.seek(0)
```
Calling `tell()` seems to get things unstuck so the following `seek` works. Just calling `seek`, even doing it multiple times, does not work. A subsequent `tell()` **still** returns -8192. The next  `seek` is successful.

One workaround is to call `tell` and `seek` as above although I hate to rely on magical incantations like that. I think a better choice would be to get rid of mmap as it is only used to find the end of the header. Assuming that the header is a reasonable size the following can replace the mmap code starting on line 241:
```
    datafilehandle.seek(0)  # Win is open in binary and others in normal mode
    chunk = datafilehandle.read(_READ_CHUNKSIZE)
    seek_past_header_pos = chunk.find(b'\n\n')
```
I only tried that on Win7-64 & python 3 so it might need adjustment for backwards compatibility.

**Comment by mhe** [comment]
Thanks for reporting, I'll check it out! mmap on Windows has resulted in issues before. Unfortunately I currently do not have access to a machine to properly test and investigate this, so there is a good chance I might ask you to do some testing for me.

**Comment by mhe** [comment]
From your reports and a quick glance at the code, I have the impression that the problem described are due to interference between the mmap calls and the regular filehandle calls. I am considering taking out the mmap stuff.

**Comment by haesemeyer** [comment]
That might be - in particular regular file calls before the mmap calls - since everything seems to be working fine if read_data is called on a "freshly opened" file, i.e. without a call to read_header first.
Maybe taking out those calls is indeed the best option. I'm happy to test a new version on Windows.

**Comment by wilkij1** [comment]
Sure, I can give it a try if you like. Let me know.

**Comment by anki-xyz** [comment]
I still need the @wilkij1 workaround! Windows 7 or Windows 10, Python 3.5 or Python 3.6. It gives different errors, depending on the Windows, though (it was zlib error -3...). With the quick workaround, everything is fine.
