### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by mhe** [mhe/pynrrd#34]
Even though this pynrrd module is fairly straightforward, additional documentation is very welcome, in particular for first-time users.

**Comment by addisonElliott** [comment]
@mhe I recently released a library called [polarTransform](https://github.com/addisonElliott/polarTransform). The purpose of the library does not matter but that it was created in Python and I created documentation using Sphinx.

If you like the format (the theme and such can be changed), we could use this as a template to get documentation in NRRD. It should be even easier than what I did for my polarTransform library.

Let me know your thoughts.

**Comment by addisonElliott** [comment]
Fixed in #60
