### ISSUE TITLE
Extracting Numpy Array from Numpy Structure

### ISSUE THREAD

**Issue by tommydino93** [mhe/pynrrd#43]
Hi everyone!
I've been trying to convert some .nrrd images into a numpy array in order to later plot them with matplotlib.

I have used the following code:

```
filtered_wavelet_images = []
filtered_wavelet_images.append(nrrd.read("decomposition_image_0.nrrd"))
filtered_wavelet_images.append(nrrd.read("decomposition_image_1.nrrd"))
filtered_wavelet_images.append(nrrd.read("decomposition_image_2.nrrd"))

first_image=filtered_wavelet_images[0]
second_image=filtered_wavelet_images[1]
third_image=filtered_wavelet_images[2]
```
and everything works fine. The only problem is that `first_image`, `second_image` and `third_image` are not numpy array, but instead they are tuples containing the numpy array. My question is:

how can I extract only the numpy array from this tuple in order to plot it later?

Thanks in advance and sorry if the question is trivial,
Tommy

**Comment by addisonElliott** [comment]
No problem. So here is what you want to do:

```
imageVolume0, imageHeader0 = nrrd.read("decomposition_image_0.nrrd")
imageVolume1, imageHeader1 = nrrd.read("decomposition_image_1.nrrd")
imageVolume2, imageHeader2 = nrrd.read("decomposition_image_2.nrrd")

filtered_wavelet_images = []
filtered_wavelet_images.append(imageVolume0)
filtered_wavelet_images.append(imageVolume1)
filtered_wavelet_images.append(imageVolume2)
```

### Explanation
If you check out [the frontpage in Usage section](https://github.com/mhe/pynrrd#example-usage), you notice that nrrd.read does return a tuple. 

The first item is a NumPy array of your volume and the second item in the tuple is a dictionary containing all of the metadata from the NRRD file. 

Another reason we should create documentation for pynrrd. Hopefully that'll be done sometime in the near future!

**Comment by addisonElliott** [comment]
@tommydino93 If this fixed your problem, do you mind closing this PR?

Really the only issue here is that we need better documentation but hopefully in the future I will get time to write some!

**Comment by tommydino93** [comment]
Thanks a lot @addisonElliott! It fixed my problem!
