### ISSUE TITLE
float32, float64

### ISSUE THREAD

**Issue by vinaym815** [mhe/pynrrd#48]
The dtype of the data I read is float32. When we create a numpy array with dtype=float the default is float64. Initially, I thought that the shebang line was responsible for it but it was not. Now after going around the code for some time, I have no idea why this is happening. I tried the replace float() in parse vector with np.float64() with no effect.

The nrrd file is available at:
https://drive.google.com/open?id=1Aabyj9TxbJP-cT02alvS1dUd5VzcO2_9

Please help

**Comment by addisonElliott** [comment]
What is your question exactly?

Are you trying to read or write a NRRD file with 32-bit data?

For writing 32-bit data, create a NumPy array with 32-bit data like this:
```
import numpy as np

data = np.array([1.0, 2.0, 3.0], dtype=np.float32)
```

I would have to test it, but I think reading the 32-bit float data will cast it to 64-bit float by default. Not sure how this would be an issue. If you require your data to be 32-bit float, then cast the NumPy array to 32-bit float.
```
import numpy as np

# data variable is 64-bit float

newData = data.astype(np.float32)
```

**Comment by addisonElliott** [comment]
Just wanted to ping this and see if your issue has been solved?

If not, can you please provide additional information regarding your issue so we can help you solve it.

**Comment by vinaym815** [comment]
Hi Elliott. Thank you for your prompt reply. The module is working as expected, it was me who was at fault. I expected that the module would read every nrrd file by default into a float64 type array, which is not the case.

**Comment by addisonElliott** [comment]
Good news then. I will close this issue.
