### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by ihnorton** [mhe/pynrrd#67]
Would it be possible to do a bump release to get the compression changes into PyPI? Thanks!

**Comment by ihnorton** [comment]
ref https://github.com/mhe/pynrrd/pull/65

**Comment by addisonElliott** [comment]
Thank you for reminding me. My initial plan was to give it some time in case another PR was accepted. But then I forgot about it!

I released version 0.3.3. The PyPi badge on the README of this project still shows 0.3.2 but I think that it will automatically update.

**Comment by ihnorton** [comment]
Many thanks! cc @tashrif-billah FYI

**Comment by tashrifbillah** [comment]
Kudos to @ihnorton! Previsouly writing `nrrd` file used to take ~95 seconds on a 32 processor machine. Now, after setting `compression_level = 1`, the same job takes only 3 seconds without any trade-off against space.

**Comment by addisonElliott** [comment]
That's great to hear.

If there are any other problems with the library (such as the performance issues you described), then it would help everyone out, including me, if you open an issue about the matter.

I'm happy to work on any issues with the library, but I need to know about them first. I don't use NRRD files **a lot** so I'm sure there are bugs/issues out there that are unknown to me.
