### ISSUE TITLE
Cannot install pynrrd via conda

### ISSUE THREAD

**Issue by prakharprakash** [mhe/pynrrd#93]
Executing the following command:
`conda install -c kayarre pynrrd`
results in the error message:
```
Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/kararre/noarch/repodata.json>
Elapsed: 00:00.195405
CF-RAY: 4c2cf5e01ad87197-ORD

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/kararre

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
```

The solution appears to be creating the noarch directory per the error message

**Comment by addisonElliott** [comment]
On phone right now, will investigate later.

Initial question, why are you using conda? I don't maintain any releases on conda.

Try `pip install pynrrd` instead

**Comment by prakharprakash** [comment]
I prefer conda over pip. No other reason.
It appears https://anaconda.org/kayarre/pynrrd is maintained by someone else. I'll see if I can ask them directly.

**Comment by addisonElliott** [comment]
I understand. I'll go ahead and close this issue.

Personally, I think `conda` and `pip` are good when used in conjunction. For a source-only library like `pynrrd` that has no C bindings, I think `pip` is fine.
