### ISSUE TITLE
coronal plane and cross section

### ISSUE THREAD

**Issue by Chida15** [mhe/pynrrd#95]
How can I get the coronal plane?why can I just get the cross section?

**Comment by addisonElliott** [comment]
Not sure I fully understand your question. You may need to elaborate.

The data returned by `pynrrd` is a Numpy data array, so slicing the data from there is up to you.

For example, here is how you could slice the coronal plane for the data:

```
import nrrd

data, header = nrrd.read('FILE_PATH_HERE')

coronalPlane20 = data[:, 20, :]
```

Please elaborate and explain your question in more detail. I'm going to close this thread in a few days if no response is given.
