### ISSUE TITLE
Need to account for both 'datafile' and 'data file'

### ISSUE THREAD

**Issue by tashrifbillah** [mhe/pynrrd#97]
We should account for both 'data file' and 'datafile' in [Ln 190](https://github.com/mhe/pynrrd/blob/master/nrrd/writer.py#L190) and [Ln 211](https://github.com/mhe/pynrrd/blob/master/nrrd/writer.py#L211) just like:
https://github.com/mhe/pynrrd/blob/master/nrrd/reader.py#L354

**Comment by addisonElliott** [comment]
:+1 I agree. Personally, I think the easiest option may be to choose one setup `data file` or `datafile` (I prefer `data file` personally) and then stick to it. Thus, have a line like:
```
if 'datafile' in self.header:
    self.header['data file'] = self.header.pop('datafile')
```

Then you can assume that there will **only** be a datafile. Just my initial thoughts.

**Comment by tashrifbillah** [comment]
Assign: @tashrifbillah
